#! /usr/bin/env python

import dynamo_consistency.datatypes as dt

# Load the remote listings generated by consistency-dump-tree
mit = dt.get_info('var/cache/T2_US_MIT/remote.pkl')
cern = dt.get_info('var/cache/T2_CH_CERN/remote.pkl')

# Compare the lists, and ignore non-ROOT files that are on EOS
# https://dynamo-consistency.readthedocs.io/en/latest/reference.html#dynamo_consistency.datatypes.compare
_ = dt.compare(inventory=cern, listing=mit, output_base='vhbb',
               missing_check=lambda x: not x.endswith('.root'))
